---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  allow_failures:
    - php: '5.4'
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit --testdox

after_failure:
  - vendor/bin/phpunit
...